language: go

go:
  - 1.9

script:
  - make deps
  - make presubmit
  - make test

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - curl -L https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o dep && chmod 700 dep && sudo mv dep /usr/local/bin/

notifications:
  email:
    on_success: never
    on_failure: never
