// Copyright 2017 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"regexp"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/golang/glog"
)

const (
	minUVMSupportedVersion = 550
	SIGRTMIN               = 34
)

var (
	readFile = os.ReadFile

	containerPathPrefix = flag.String("container-path", "/usr/local/nvidia", "Path on the container that mounts host nvidia install directory")
	cgpuConfigFile      = flag.String("cgpu-config", "/etc/nvidia/confidential_node_type.txt", "File with Confidential Node Type used on Node")
	machineTypeFile     = flag.String("machine-type-file", "/etc/nvidia/machine_type.txt", "File with the Machine Type used on Node")
	readyDelay          = flag.Int64("ready-delay-ms", 1000, "How much time to wait before setting GPU to ready state. Adding a delay helps to reduce the chances of a start up error.")
)

func main() {
	flag.Parse()
	ctx := context.Background()

	// Only run persistence daemon on confidential GPU nodes.
	enabled, err := checkConfidentialGPUEnablement(ctx)
	if err != nil {
		glog.ExitContextf(ctx, "parseCGPUConfig failed: %v", err)
	}

	if enabled {
		// This is necessary to be able to use nvidia smi from the container to set the GPU to a ready state.
		if err := updateContainerLdCache(); err != nil {
			glog.ExitContextf(ctx, "updateContainerLdCache failed: %v", err)
		}

		if err := enablePersistenceMode(ctx); err != nil {
			glog.ExitContextf(ctx, "failed to start persistence mode: %v", err)
		}
		// Add small delay before setting the ready state for consistency.
		// If the workload starts too close to when the persistence daemon has started sometimes there can be errors.
		time.Sleep(time.Duration(*readyDelay) * time.Millisecond)

		// Mark GPU with ready state. If encounter no devices were found issue, reboot the node.
		if output, err := setGPUReadyState(ctx); err != nil {
			glog.Infof("failed to set gpu to ready state: %v, output: %s", err, output)
			if strings.Contains(output, "No devices were found") {
				glog.Infof("No devices were found, rebooting node to resolve")
				if err := rebootNode(); err != nil {
					glog.Errorf("Failed to trigger node reboot: %v", err)
				}
			}
			// Exit, since we cannot proceed when encounter error.
			os.Exit(1)
		}
	} else {
		glog.InfoContext(ctx, "Confidential GPU is NOT enabled, skipping nvidia persistenced enablement.")
		// Don't exit as this is intended for a side car which would cause it to restart infinitely.
	}

	// Read machine type from the file generated by the initContainer
	machineType, err := getMachineTypeFromFile(ctx)
	if err != nil {
		glog.WarningContextf(ctx, "Failed to get machine type: %v", err)
	} else if err := enableGriddDaemon(ctx, machineType); err != nil {
		glog.WarningContextf(ctx, "Failed to enable nvidia-gridd: %v", err)
	}

	// Need to keep the container running so that the nvidia persistence daemon can keep running.
	// Create a channel to listen for termination signals (SIGINT and SIGTERM)
	sigChan := make(chan os.Signal, 1)
	signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)

	// Block indefinitely until a signal is received
	sig := <-sigChan
	fmt.Printf("Received signal: %v. Shutting down...\n", sig)
}

func enablePersistenceMode(ctx context.Context) error {
	glog.InfoContext(ctx, "Starting NVIDIA persistence daemon.")
	cmdArgs := []string{}
	if versionMajor, err := nvidiaVersionMajor(ctx); err != nil {
		return err
	} else if versionMajor >= minUVMSupportedVersion {
		// UVM persistence mode is only available starting at R550.
		cmdArgs = append(cmdArgs, "--uvm-persistence-mode")
		glog.InfoContext(ctx, "using --uvm-persistence-mode")
	}
	cmdArgs = append(cmdArgs, "--nvidia-cfg-path="+*containerPathPrefix+"/lib64")
	persistencedCMD := exec.Command(*containerPathPrefix+"/bin/nvidia-persistenced", cmdArgs...)
	if err := persistencedCMD.Run(); err != nil {
		return err
	}
	glog.InfoContext(ctx, "NVIDIA Persistence Mode Enabled.")
	return nil
}

func setGPUReadyState(ctx context.Context) (string, error) {
	gpuReadyCMD := exec.Command(*containerPathPrefix+"/bin/nvidia-smi", "conf-compute", "-srs", "1")
	if output, err := gpuReadyCMD.CombinedOutput(); err != nil {
		return string(output), err
	}
	glog.InfoContext(ctx, "Confidential GPU is ready.")
	return "", nil
}

func updateContainerLdCache() error {
	f, err := os.Create("/etc/ld.so.conf.d/nvidia.conf")
	if err != nil {
		f.Close()
		return fmt.Errorf("failed to update ld cache: %w", err)
	}
	f.WriteString(*containerPathPrefix + "/lib64")
	f.Close()
	err = exec.Command("ldconfig").Run()
	if err != nil {
		return fmt.Errorf("failed to update ld cache: %w", err)
	}
	return nil
}

func getLoadedNVIDIAKernelModuleVersion(ctx context.Context, versionFilePath string) string {
	glog.InfoContextf(ctx, "Attempting to read nvidia gpu driver version from: %s", versionFilePath)
	content, err := os.ReadFile(versionFilePath)
	if err != nil {
		glog.ErrorContextf(ctx, "Failed to read version file: %v", err)
		return ""
	}
	contentStr := string(content)
	kernelModuleVersionPattern := regexp.MustCompile(`\d+\.\d+\.\d+`)
	kernelModuleVersion := kernelModuleVersionPattern.FindString(contentStr)
	glog.InfoContextf(ctx, "nvidia gpu driver version: %s", kernelModuleVersion)
	return kernelModuleVersion
}

func nvidiaVersionMajor(ctx context.Context) (int, error) {
	version := getLoadedNVIDIAKernelModuleVersion(ctx, "/proc/driver/nvidia/version")
	if version == "" {
		return 0, fmt.Errorf("failed to read nvidia gpu driver version at /proc/driver/nvidia/version")
	}

	// Will be in this format as it was validated by the regex beforehand: 535.230.02
	before, _, found := strings.Cut(version, ".")
	if !found || len(before) != 3 {
		return 0, fmt.Errorf("invalid nvidia gpu driver version: %v", version)
	}

	versionMajor, err := strconv.Atoi(before)
	if err != nil {
		return 0, fmt.Errorf("invalid nvidia gpu driver version(%v), %w", version, err)
	}
	return versionMajor, nil
}

func checkConfidentialGPUEnablement(ctx context.Context) (bool, error) {
	file, err := readFile(*cgpuConfigFile)
	if err != nil {
		// Treat non existence of file as disabled.
		if os.IsNotExist(err) {
			glog.InfoContextf(ctx, "confidential node type file not found at %v, skipping persistenced installation", *cgpuConfigFile)
			return false, nil
		}
		return false, err
	}
	// Remove any trailing spaces and null strings to avoid issues in comparison.
	confidentialNodeType := strings.ToLower(strings.Trim(string(file), " \r\n\x00"))
	return confidentialNodeType == "tdx", nil
}

func rebootNode() error {
	// Gracefully reboot systemd: https://man7.org/linux/man-pages/man1/systemd.1.html#SIGNALS
	return syscall.Kill(1, SIGRTMIN+5)
}

func getMachineTypeFromFile(ctx context.Context) (string, error) {
	file, err := readFile(*machineTypeFile)
	if err != nil {
		if os.IsNotExist(err) {
			glog.InfoContextf(ctx, "machine type file not found at %v", *machineTypeFile)
			return "", nil
		}
		return "", err
	}
	return strings.TrimSpace(string(file)), nil
}

func enableGriddDaemon(ctx context.Context, machineType string) error {
	const (
		G4_STANDARD_6  = "g4-standard-6"
		G4_STANDARD_12 = "g4-standard-12"
		G4_STANDARD_24 = "g4-standard-24"
	)

	if machineType != G4_STANDARD_6 && machineType != G4_STANDARD_12 && machineType != G4_STANDARD_24 {
		glog.InfoContextf(ctx, "Machine type %s does not require nvidia-gridd.", machineType)
		return nil
	}

	griddPath := *containerPathPrefix + "/bin/nvidia-gridd"
	griddLibsPath := *containerPathPrefix + "/gridd-libs"

	glog.InfoContextf(ctx, "Waiting for %s to appear...", griddPath)
	for {
		if _, err := os.Stat(griddPath); err == nil {
			glog.InfoContextf(ctx, "Found %s, proceeding to start daemon.", griddPath)
			break
		}
		time.Sleep(10 * time.Second)
	}

	rootMountDir := os.Getenv("ROOT_MOUNT_DIR")
	if rootMountDir == "" {
		rootMountDir = "/root"
	}

	// Link necessary libraries manually
	hostLib64 := rootMountDir + "/lib64"
	hostUsrLib64 := rootMountDir + "/usr/lib64"
	linkerPath := rootMountDir + "/lib64/ld-linux-x86-64.so.2"

	glog.InfoContextf(ctx, "Waiting for dynamic linker %s to appear...", linkerPath)
	for {
		if _, err := os.Stat(linkerPath); err == nil {
			break
		}
		time.Sleep(10 * time.Second)
	}

	glog.InfoContextf(ctx, "Starting nvidia-gridd daemon via host dynamic linker: %s", linkerPath)

	libPathStr := strings.Join([]string{griddLibsPath, hostLib64, hostUsrLib64}, ":")
	cmd := exec.Command(linkerPath, "--library-path", libPathStr, griddPath)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to run nvidia-gridd: %w, output: %s", err, string(output))
	}

	glog.InfoContext(ctx, "nvidia-gridd daemon started.")
	return nil
}
